// Screenshots: crops of real app screenshots (assets/shots/manifest.json) into
// AVIF and WebP at a few widths, and src/lib/shots.ts for the pages to read.
//   npm run images
import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";

interface Crop { left: number; top: number; width: number; height: number }
interface Shot { key: string; file: string; crop?: Crop; alt: string; caption: string; phone?: Crop }

const root = path.resolve(import.meta.dirname, "..");
const manifestFile = path.join(root, "assets/shots/manifest.json");
const outDir = path.join(root, "public/shots");
const registry = path.join(root, "src/lib/shots.ts");
const WIDTHS = [640, 960, 1440, 1920];

const manifest: Shot[] = fs.existsSync(manifestFile) ? JSON.parse(fs.readFileSync(manifestFile, "utf8")) : [];
fs.mkdirSync(outDir, { recursive: true });

async function variants(input: string, crop: Crop | undefined, name: string, widths: number[], formats: ("avif" | "webp")[]) {
  const done: number[] = [];
  for (const w of widths) {
    for (const f of formats) {
      const out = path.join(outDir, `${name}-${w}.${f}`);
      if (!fs.existsSync(out) || fs.statSync(out).mtimeMs < fs.statSync(input).mtimeMs || fs.statSync(out).mtimeMs < fs.statSync(manifestFile).mtimeMs) {
        let img = sharp(input);
        if (crop) img = img.extract(crop);
        img = img.resize({ width: w, withoutEnlargement: true });
        await (f === "avif" ? img.avif({ quality: 58, effort: 6 }) : img.webp({ quality: 80 })).toFile(out);
      }
    }
    done.push(w);
  }
  return done;
}

const entries: Record<string, unknown> = {};
for (const s of manifest) {
  const input = path.join(root, "assets/shots", s.file);
  const meta = await sharp(input).metadata();
  const box = s.crop ?? { left: 0, top: 0, width: meta.width!, height: meta.height! };
  const widths = WIDTHS.filter(w => w <= box.width);
  if (!widths.length) widths.push(box.width);
  await variants(input, s.crop, s.key, widths, ["avif", "webp"]);
  const entry: Record<string, unknown> = { width: box.width, height: box.height, widths, alt: s.alt, caption: s.caption };
  if (s.phone) entry.phone = { widths: await variants(input, s.phone, `${s.key}-phone`, WIDTHS.filter(w => w <= s.phone!.width).slice(0, 2), ["avif"]) };
  entries[s.key] = entry;
}

const source = `// Generated by scripts/images.ts from assets/shots/manifest.json. Do not edit.
export const shots: Record<string, { width: number; height: number; widths: number[]; alt: string; caption: string; phone?: { widths: number[] } }> = ${JSON.stringify(entries, null, 2)};
`;
if (!fs.existsSync(registry) || fs.readFileSync(registry, "utf8") !== source) fs.writeFileSync(registry, source);
console.log(`images: ${manifest.length} screenshots`);
