// Generated by scripts/images.ts from assets/shots/manifest.json. Do not edit.
export const shots: Record<string, { width: number; height: number; widths: number[]; alt: string; caption: string; phone?: { widths: number[] } }> = {};
